"""Pin camera preprocessing and flash CRC for a compiled optical-flow model.

Run in the isolated TensorFlow conversion environment. Does not flash hardware.
"""
import argparse
import hashlib
import json
import re
from pathlib import Path
import zlib
import numpy as np
import tensorflow as tf

p = argparse.ArgumentParser(description=__doc__)
p.add_argument('model', type=Path)
p.add_argument('--name', choices=['edge', 'MCUFlowNet-S', 'MCUFlowNet-L'], required=True)
p.add_argument('--out', type=Path, required=True)
a = p.parse_args()
root = Path(__file__).resolve().parents[1]
data = a.model.read_bytes()
# Keep the historical slot when possible; larger models need an earlier start.
flash_address = 0xB7B000 if len(data) <= 0x1000000 - 0xB7B000 else 0xA00000
assert flash_address + len(data) <= 0x1000000
common = root / 'EPII_CM55M_APP_S/app/scenario_app/optical_cam_oflow/config/common_config.h'
common_text, count = re.subn(r'(#define OPTICAL_FLOW_MODEL_FLASH_ADDR )0x[0-9A-Fa-f]+',
    lambda m: m[1] + f'0x{0x3A000000 + flash_address:08X}', common.read_text())
assert count == 1
common.write_text(common_text, encoding='utf-8')
it = tf.lite.Interpreter(model_path=str(a.model))
ii, oo = it.get_input_details()[0], it.get_output_details()[0]
shape, output = ii['shape'].tolist(), oo['shape'].tolist()
assert ii['dtype'] == oo['dtype'] == np.int8
assert shape[0] == output[0] == 1 and shape[-1] == 6 and output[-1] == 2
scale, zero = ii['quantization']
assert scale > 0
x = np.arange(256, dtype=np.float32)
if a.name != 'edge':
    x = x / 255 * 2 - 1
lut = np.clip(np.rint(x / scale + zero), -128, 127).astype(np.int8)
# Exactly the preprocessing used by export_grove/evaluate_grove, all byte values.
assert np.all(np.diff(lut.astype(np.int16)) >= 0)
crc = zlib.crc32(data)
name = f'{a.name}-{shape[2]}x{shape[1]}'
header = root / 'EPII_CM55M_APP_S/app/scenario_app/optical_cam_oflow/config/bench_model.h'
header.write_text(
    '// Generated by tools/prepare_optical_bench.py; also archived in the build.\n'
    f'#define FLOW_BENCH_NAME "{name}"\n#define FLOW_BENCH_BYTES {len(data)}U\n'
    f'#define FLOW_BENCH_CRC 0x{crc:08x}U\n'
    f'#define FLOW_BENCH_OUTPUT_MULTIPLIER {1.0 if a.name == "edge" else 12.5}f\n'
    'static const int8_t flow_bench_input_lut[256] = {' + ','.join(map(str, lut.tolist())) + '};\n',
    encoding='utf-8')
profile = dict(schema_version=1, id=name.lower(), mode='deploy', app='optical_cam_oflow', camera='OV5647',
    device=dict(vid='0x1A86', pid='0x55D3', baud=921600),
    models=[dict(path=str(a.model.resolve()), sha256=hashlib.sha256(data).hexdigest(), address=hex(flash_address), offset='0x0')],
    flash=dict(size='0x1000000', firmware_region=['0x0', '0x171000']),
    verify=dict(required=[f'FLOW_MODEL {name} crc={crc:08x} PASS', 'camera input init done',
        'Ethos-U55 device initialised', 'initial done'], forbidden_regex=['(?i)\\bfail(?:ed|ure)?\\b'],
        input_shape=shape, output_shape=output, min_frames=3, frame_resolution=[output[2], output[1]]),
    notes='Camera runtime check; LUT matches host INT8 preprocessing; CRC checks flash content, not cryptographic attestation. JPEG is not EPE evidence.')
a.out.mkdir(parents=True, exist_ok=False)
(a.out / 'profile.json').write_text(json.dumps(profile, indent=2) + '\n', encoding='utf-8')
(a.out / 'bench_model.h').write_bytes(header.read_bytes())
(a.out / 'io.json').write_text(json.dumps(dict(input_quantization=ii['quantization'],
    output_quantization=oo['quantization'], input_lut=lut.tolist(), crc32=f'{crc:08x}',
    output_multiplier=1 if a.name == 'edge' else 12.5), indent=2) + '\n', encoding='utf-8')
print(a.out / 'profile.json')
